// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMIVDn1-Dp9sjUhdBfEQ8bkdGfySYfCCI',
    appId: '1:88241417941:web:5f1fb1d3bfde14fd643c5c',
    messagingSenderId: '88241417941',
    projectId: 'ment-ally-a207a',
    authDomain: 'ment-ally-a207a.firebaseapp.com',
    storageBucket: 'ment-ally-a207a.appspot.com',
    measurementId: 'G-S0NYVTQLNH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSSdOqEq8tFtEg9xvF2BZFZZo-EaXy_VM',
    appId: '1:88241417941:android:cfb618febe288ed3643c5c',
    messagingSenderId: '88241417941',
    projectId: 'ment-ally-a207a',
    storageBucket: 'ment-ally-a207a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJDbPkL8UrVzJUombr5bwbppOB6LFK6c4',
    appId: '1:88241417941:ios:cea870706a6b3bcc643c5c',
    messagingSenderId: '88241417941',
    projectId: 'ment-ally-a207a',
    storageBucket: 'ment-ally-a207a.appspot.com',
    iosBundleId: 'com.example.project1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJDbPkL8UrVzJUombr5bwbppOB6LFK6c4',
    appId: '1:88241417941:ios:9609b20541637be5643c5c',
    messagingSenderId: '88241417941',
    projectId: 'ment-ally-a207a',
    storageBucket: 'ment-ally-a207a.appspot.com',
    iosBundleId: 'com.example.project1.RunnerTests',
  );
}
